# Maximum rating player can give players in total
# Can be overwritten in LuckPerms
maxRatingPerDay: 10
# Maximum rating player can give another player per day
# Can be overwritten in LuckPerms
maxRatingPerPlayer: 3
# Check if player, which creates report need linked DiscordSRV
needDiscordLinked: false
# Minimum time played on server required to add players rating
# In milliseconds
# ex: 1 hours = 1h*60m*60s*1000ms = 3600000
minTimeOnServer: 3600000
# Minimum time on discord required to let rating on players
# In milliseconds
# ex: 1 hours = 1h*60m*60s*1000ms = 3600000
minTimeOnDiscord: 3600000
# As it says
minMessageLength: 5
# As it says
maxMessageLength: 30
# If message length equals 30 and trimMessageAfter=15 then message will be separated into two rows
trimMessageAfter: 15
# If set false then trim will not cut words
cutWords: false
# Use only one!!!
# MySql has higher priority!!!
databaseConnection:
  sqlite: true
  #mysql:
  #  database: "my_database_name"
  #  host: "127.0.0.1"
  #  port: 3306
  #  username: "my_username"
  #  password: "XXX_SUPER_PASSWORD_SECURITY"
# Color are sorted by value: [-10, -5, 0, 5, 10]
# Be sure to fill ALL GAPS/INTERVALS - if not you'll have errors in console
# If you don't want this feature - remove coloring section or comment it using '#' symbol
#coloring:
#  # If <-5 -> #eb3131
#  - less: -5
#    color: #eb3131
#  # If <-10 -> #9c0303
#  - less: -10
#    color: #9c0303
#  # If <0 -> #FFFFFF
#  - less: 0
#    color: #FFFFFF
#  # If ==0 -> #FFFFFF
#  - equal: 0
#    color: #FFFFFF
#  # If >0 -> #FFFFFF
#  - more: 0
#    color: #FFFFFF
#  # If >5 -> #51a8f5
#  - more: 5
#    color: #51a8f5
#  # If >10 -> #0872cf
#  - more: 10
#    color: #0872cf

gui:
  showFirstConnection: true
  showLastConnection: true
  showDeleteReport: true
  # Don't modify this if you don't know how it works
  format: "yyyy-MM-dd"
  # Buttons in GUI
  buttons:
    back:
      material: PAPER
      customModelData: 0
    prev:
      material: PAPER
      customModelData: 0
    next:
      material: PAPER
      customModelData: 0
    sort:
      material: SUNFLOWER
      customModelData: 0