# Maximum rating player can give players in total
# Can be overwritten in LuckPerms
maxRatingPerDay: 50
# Maximum rating player can give another player per day
# Can be overwritten in LuckPerms
maxRatingPerPlayer: 10
# Check if player, which creates report need linked DiscordSRV
needDiscordLinked: false
# Minimum time played on server required to add players rating
minTimeOnServer: 10
# Minimum time on discord required to let rating on players
minTimeOnDiscord: 10
